### ISSUE TITLE
src subdir should be same as ros package

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/grammar_parser#2]
src subdir should be same as ros package according to ROS standards

**Comment by LoyVanBeek** [comment]
I know, has been fixed, but somehow this commit is not yet reflected on github due to their downtime yesterday. 
Will fix those weird commits on Saturday.

**Comment by LoyVanBeek** [comment]
The same goes for a new branch of nl_robot_console and action_server, which then use this package as a dependency.

**Comment by LoyVanBeek** [comment]
What the actual fuck:
```bash
$ git rev-parse HEAD
1bbba1bf1f30fce395410f64c76b279bdc734359

$ git log
commit 1bbba1bf1f30fce395410f64c76b279bdc734359
Author: Loy...
Date:   Tue Dec 6 21:03:37 2016 +0100

    Move nl_robot_console package to grammar_parser

commit 0f368fee0e048acf6e3a009e1fe145a63c0a8a9e
Author: Loy van Beek <loy.vanbeek@gmail.com>
Date:   Tue Dec 6 20:48:09 2016 +0100

    Use setup.py in Catkin

commit 1fac7192af6ae957960b8f6e7b04287bfa43d466
Author: Loy...
Date:   Tue Dec 6 20:45:35 2016 +0100

    Fix package.xml

commit dc7b949187e3e70691760bb52076eae7edeebd0b
Author: Loy...
Date:   Tue Dec 6 20:36:00 2016 +0100

    Remove srv, which do not belong here
```
but on GitHub, my latest commit is  1fac719

**Comment by LoyVanBeek** [comment]
But fixed by adding another commit https://github.com/tue-robotics/grammar_parser/commit/9746c9313c3b319a920a9e2ca98aa4880ab4beab
